baseURL = "https://arfankurnianto.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "6"
summaryLength = "15"
theme = "bigspring"
title = "Ngetestdd"
[markup.goldmark.renderer]
unsafe = true
