baseURL = "https://arfankurnianto.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "TestHugo"
[markup.goldmark.renderer]
unsafe = true
